{
  "hash": "1b23ae222ea9903d1fb7ba264c37711e",
  "result": {
    "engine": "knitr",
    "markdown": "# Tables that accompany figures\n\n\n\nMany manuscript figures are paired with a small numeric table: a\nnumbers-at-risk strip below a Kaplan-Meier curve, or the count panel\nbeneath a longitudinal participation bar chart. The `hvtiPlotR` plot\nobjects carry these companion tables alongside the plot data, so we can\npull the numbers straight out and render them with `gt`. As with the\n[publication tables](qt_tables.qmd) chapter, **these tables will migrate\nto the planned hvtiRtables package** once it is available.\n\n## Numbers at risk\n\n`hv_survival()` stores its companion tables in the object's `$tables`\nslot. The numbers-at-risk strip lives in `$tables$risk` (one row per\nstrata × report-time) and the per-time-point summary in `$tables$report`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm <- hv_survival(sample_survival_data(n = 500, seed = 42))\nnames(km$tables)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"risk\"   \"report\"\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(km$tables$risk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t6 obs. of  3 variables:\n $ strata     : chr  \"All\" \"All\" \"All\" \"All\" ...\n $ report_time: num  1 5 10 15 20 25\n $ n.risk     : num  478 412 322 260 207 207\n```\n\n\n:::\n:::\n\n\nWe render the at-risk table directly with `gt`, relabelling the columns\nfor presentation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm$tables$risk |>\n  gt() |>\n  tab_header(\n    title = \"Numbers at Risk\",\n    subtitle = \"Patients remaining under follow-up at each report time\"\n  ) |>\n  cols_label(\n    strata      = \"Stratum\",\n    report_time = \"Time (years)\",\n    n.risk      = \"At risk (n)\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Numbers at Risk\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Patients remaining under follow-up at each report time\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrr}\n\\toprule\nStratum & Time (years) & At risk (n) \\\\ \n\\midrule\\addlinespace[2.5pt]\nAll & 1 & 478 \\\\ \nAll & 5 & 412 \\\\ \nAll & 10 & 322 \\\\ \nAll & 15 & 260 \\\\ \nAll & 20 & 207 \\\\ \nAll & 25 & 207 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nThe companion report table carries the survival estimates and confidence\nlimits at the same report times — useful as the figure caption's numeric\nbacking.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkm$tables$report |>\n  gt() |>\n  tab_header(title = \"Survival Estimates at Report Times\") |>\n  cols_label(\n    strata      = \"Stratum\",\n    report_time = \"Time (years)\",\n    surv        = \"S(t)\",\n    lower       = \"95% LCL\",\n    upper       = \"95% UCL\",\n    n.risk      = \"At risk\",\n    n.event     = \"Events\"\n  ) |>\n  fmt_number(columns = c(surv, lower, upper), decimals = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Survival Estimates at Report Times\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrrr}\n\\toprule\nStratum & Time (years) & S(t) & 95\\% LCL & 95\\% UCL & At risk & Events \\\\ \n\\midrule\\addlinespace[2.5pt]\nAll & 1 & 0.954 & 0.932 & 0.969 & 478 & 1 \\\\ \nAll & 5 & 0.822 & 0.786 & 0.853 & 412 & 1 \\\\ \nAll & 10 & 0.642 & 0.599 & 0.683 & 322 & 1 \\\\ \nAll & 15 & 0.518 & 0.474 & 0.562 & 260 & 1 \\\\ \nAll & 20 & 0.414 & 0.372 & 0.458 & 207 & 0 \\\\ \nAll & 25 & 0.414 & 0.372 & 0.458 & 207 & 0 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n## Longitudinal count table\n\n`hv_longitudinal()` produces a two-panel figure: a grouped bar chart of\nparticipation counts and a numeric table panel below it. The underlying\ncounts live in the object's `$data` slot in long format (one row per\ntime-window × series), with the column roles recorded in `$meta`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlc <- hv_longitudinal(sample_longitudinal_counts_data(n_patients = 300, seed = 42L))\nnames(lc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data\"   \"meta\"   \"tables\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlc$meta[c(\"x_col\", \"group_col\", \"count_col\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$x_col\n[1] \"time_label\"\n\n$group_col\n[1] \"series\"\n\n$count_col\n[1] \"count\"\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(lc$data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t14 obs. of  3 variables:\n $ time_label: Factor w/ 7 levels \"≥0 Days\",\"≥1 Month\",..: 1 2 3 4 5 6 7 1 2 3 ...\n $ series    : chr  \"Patients\" \"Patients\" \"Patients\" \"Patients\" ...\n $ count     : int  19 47 49 100 159 101 276 19 50 56 ...\n```\n\n\n:::\n:::\n\n\nWe reshape the long counts into a wide table — one row per follow-up\nwindow, one column per series — and render it with `gt`. This is the\ntabular companion to the bar chart's table panel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlc_wide <- lc$data |>\n  tidyr::pivot_wider(\n    names_from  = series,\n    values_from = count\n  )\nlc_wide\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 x 3\n  time_label Patients Measurements\n  <fct>         <int>        <int>\n1 ≥0 Days          19           19\n2 ≥1 Month         47           50\n3 ≥3 Months        49           56\n4 ≥6 Months       100          118\n5 ≥1 Year         159          217\n6 ≥2 Years        101          113\n7 ≥2.5 Years      276          620\n```\n\n\n:::\n\n```{.r .cell-code}\nlc_wide |>\n  gt(rowname_col = \"time_label\") |>\n  tab_header(\n    title    = \"Longitudinal Participation Counts\",\n    subtitle = \"Patients and measurements at each follow-up window\"\n  ) |>\n  fmt_number(columns = where(is.numeric), decimals = 0) |>\n  tab_stubhead(label = \"Follow-up window\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Longitudinal Participation Counts\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Patients and measurements at each follow-up window\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}l|rr}\n\\toprule\nFollow-up window & Patients & Measurements \\\\ \n\\midrule\\addlinespace[2.5pt]\n≥0 Days & 19 & 19 \\\\ \n≥1 Month & 47 & 50 \\\\ \n≥3 Months & 49 & 56 \\\\ \n≥6 Months & 100 & 118 \\\\ \n≥1 Year & 159 & 217 \\\\ \n≥2 Years & 101 & 113 \\\\ \n≥2.5 Years & 276 & 620 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nFor reference, the same counts rendered as the in-figure table panel\nappear below the bar chart when the two are composed with `patchwork`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_bar <- plot(lc) +\n  scale_fill_manual(\n    values = c(Patients = \"steelblue\", Measurements = \"firebrick\"),\n    name   = NULL\n  ) +\n  labs(x = NULL, y = \"Count (n)\")\n\np_tbl <- plot(lc, type = \"table\") +\n  scale_colour_manual(\n    values = c(Patients = \"steelblue\", Measurements = \"firebrick\"),\n    guide  = \"none\"\n  )\n\np_bar / p_tbl + plot_layout(heights = c(3, 1))\n```\n\n::: {.cell-output-display}\n![](figure_tables_files/figure-pdf/lc_figure-1.pdf){fig-pos='H'}\n:::\n:::\n\n",
    "supporting": [
      "figure_tables_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_risk_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"km_report_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\",\"lc_table_gt\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}