project:
  type: book
  output-dir: _book

book:
  title: "HVTI ggplot graphics recipes"
  subtitle: "Version 2.1"
  author: "John Ehrlinger <ehrlinj@ccf.org>"
  date: today
  page-navigation: true
  page-footer:
    left: "Copyright 2025, John Ehrlinger"
    right:
      - icon: github
        href: https://github.com/ehrlinger/hvti_graphics
  chapters:
    - index.qmd
    - intro.qmd
    - part: gettingstarted.qmd
      chapters:
        - packages.qmd
        - usingR.qmd
        - data_governance.qmd
    - part: formatting.qmd
      chapters:
        - annotation.qmd
        - themes.qmd
        - colors.qmd
        - legends.qmd
    - part: timetoevent.qmd
      chapters:
        - survival.qmd
        - hazard.qmd
        - temporal_hazard.qmd
        - nnt.qmd
    - part: distributions.qmd
      chapters:
        - histograms.qmd
        - density.qmd
        - boxplots.qmd
        - bar.qmd
    - part: relationships.qmd
      chapters:
        - scatter.qmd
        - spaghetti.qmd
        - postagestamp.qmd
        - upset.qmd
    - part: specialty.qmd
      chapters:
        - consort.qmd
        - sankey.qmd
        - balance.qmd
    - part: randomforests.qmd
      chapters:
        - rf_error.qmd
        - rf_predicted.qmd
        - rf_vimp.qmd
        - rf_dependence.qmd
        - rf_roc.qmd
        - varpro.qmd
        - varpro_partial.qmd
    - part: tables.qmd
      chapters:
        - qt_tables.qmd
        - figure_tables.qmd
    - part: publications.qmd
      chapters:
        - combination.qmd
        - manuscripts.qmd
        - researchday.qmd
        - presentations.qmd
    - summary.qmd
    - references.qmd

bibliography:
  - references.bib
  - packages.bib

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: true
    toc: true
    toc-depth: 3
  pdf:
    documentclass: scrreprt
    keep-tex: true

execute:
  freeze: auto

editor: source
