{
  "hash": "3b9aed5add276b7599a93c56122ce5a7",
  "result": {
    "engine": "knitr",
    "markdown": "# Publication tables\n\nFor a thorough treatment of effective display tables in `gt` [@R-gt], see\nRich Iannone's guide:\n<https://rich-iannone.github.io/gt-effective-display-tables/>.\n\n\n\nThis chapter builds publication-ready tables directly with the `gt`\npackage. The recipes here are deliberately self-contained; once a\ndedicated table package matures, **these tables will migrate to the\nplanned hvtiRtables package** and the call sites will collapse to a\nsingle helper.\n\n## A \"Table 1\" baseline-characteristics summary\n\nThe canonical first table in any clinical manuscript is a\nbaseline-characteristics summary (\"Table 1\"): rows of patient\ncharacteristics, columns split by treatment or exposure group. We build\none from `hvtiRutilities::generate_survival_data()`, which returns a\nrichly labelled patient-level cohort with a natural grouping variable\n(`sex`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndta <- hvtiRutilities::generate_survival_data(n = 200, seed = 42)\nstr(dta[, c(\"sex\", \"age\", \"bmi\", \"gfr_bs\", \"diabetes\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t200 obs. of  5 variables:\n $ sex     : Factor w/ 2 levels \"Female\",\"Male\": 2 2 1 2 1 2 1 2 2 2 ...\n  ..- attr(*, \"label\")= chr \"Sex\"\n $ age     : num  65.6 36.5 50.4 54.5 51.1 43.4 67.7 43.6 75.3 44.1 ...\n  ..- attr(*, \"label\")= chr \"Age at surgery (years)\"\n $ bmi     : num  27 30.8 27.2 30.7 26.3 26.7 29.4 32 20.8 26.8 ...\n  ..- attr(*, \"label\")= chr \"Body mass index (kg/m2)\"\n $ gfr_bs  : num  62 54.9 64.3 72.8 87 83.3 72.9 57.9 97.5 93.3 ...\n  ..- attr(*, \"label\")= chr \"Baseline eGFR (mL/min/1.73m2)\"\n $ diabetes: Factor w/ 2 levels \"No\",\"Yes\": 1 1 1 2 1 1 1 2 1 1 ...\n  ..- attr(*, \"label\")= chr \"Diabetes mellitus\"\n```\n\n\n:::\n:::\n\n\n### Summarise numeric variables as mean ± SD\n\nWe summarise three continuous baseline variables (age, BMI, baseline\neGFR) as mean and standard deviation within each `sex` group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_summary <- dta |>\n  group_by(sex) |>\n  summarise(\n    n        = dplyr::n(),\n    age_mean = mean(age),     age_sd = sd(age),\n    bmi_mean = mean(bmi),     bmi_sd = sd(bmi),\n    gfr_mean = mean(gfr_bs),  gfr_sd = sd(gfr_bs),\n    .groups  = \"drop\"\n  )\nnum_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 8\n  sex        n age_mean age_sd bmi_mean bmi_sd gfr_mean gfr_sd\n  <fct>  <int>    <dbl>  <dbl>    <dbl>  <dbl>    <dbl>  <dbl>\n1 Female    77     45.1   14.8     27.1   4.89     76.6   20.5\n2 Male     123     44.3   14.5     26.6   4.67     75.9   18.7\n```\n\n\n:::\n:::\n\n\n### Summarise a categorical variable as n (%)\n\nDiabetes status is summarised as a count and within-group percentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_summary <- dta |>\n  group_by(sex) |>\n  summarise(\n    diabetes_n   = sum(diabetes == \"Yes\"),\n    diabetes_pct = 100 * mean(diabetes == \"Yes\"),\n    .groups      = \"drop\"\n  )\ncat_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 3\n  sex    diabetes_n diabetes_pct\n  <fct>       <int>        <dbl>\n1 Female         17         22.1\n2 Male           38         30.9\n```\n\n\n:::\n:::\n\n\n### Render with `gt()`\n\nWe join the two summaries and present the result with a header, relabelled\ncolumns, and consistent numeric formatting. Mean ± SD pairs are formatted\nto one decimal place; the diabetes percentage to one decimal place.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable1 <- num_summary |>\n  left_join(cat_summary, by = \"sex\") |>\n  gt(rowname_col = \"sex\") |>\n  tab_header(\n    title    = \"Table 1. Baseline Characteristics by Sex\",\n    subtitle = \"Simulated cohort, n = 200\"\n  ) |>\n  cols_label(\n    n            = \"N\",\n    age_mean     = \"Age (mean)\",\n    age_sd       = \"Age (SD)\",\n    bmi_mean     = \"BMI (mean)\",\n    bmi_sd       = \"BMI (SD)\",\n    gfr_mean     = \"eGFR (mean)\",\n    gfr_sd       = \"eGFR (SD)\",\n    diabetes_n   = \"Diabetes (n)\",\n    diabetes_pct = \"Diabetes (%)\"\n  ) |>\n  fmt_number(\n    columns  = c(age_mean, age_sd, bmi_mean, bmi_sd,\n                 gfr_mean, gfr_sd, diabetes_pct),\n    decimals = 1\n  ) |>\n  tab_spanner(label = \"Age (years)\",  columns = c(age_mean, age_sd)) |>\n  tab_spanner(label = \"BMI (kg/m²)\",  columns = c(bmi_mean, bmi_sd)) |>\n  tab_spanner(label = \"eGFR (mL/min)\", columns = c(gfr_mean, gfr_sd))\n\ntable1\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Table 1. Baseline Characteristics by Sex\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Simulated cohort, n = 200\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}l|rrrrrrrrr}\n\\toprule\n &  & \\multicolumn{2}{c}{{Age (years)}} & \\multicolumn{2}{c}{{BMI (kg/m²)}} & \\multicolumn{2}{c}{{eGFR (mL/min)}} &  &  \\\\ \n\\cmidrule(lr){3-4} \\cmidrule(lr){5-6} \\cmidrule(lr){7-8}\n & N & Age (mean) & Age (SD) & BMI (mean) & BMI (SD) & eGFR (mean) & eGFR (SD) & Diabetes (n) & Diabetes (\\%) \\\\ \n\\midrule\\addlinespace[2.5pt]\nFemale & 77 & 45.1 & 14.8 & 27.1 & 4.9 & 76.6 & 20.5 & 17 & 22.1 \\\\ \nMale & 123 & 44.3 & 14.5 & 26.6 & 4.7 & 75.9 & 18.7 & 38 & 30.9 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nThe table renders as static HTML in the book and as a publication-quality\nPDF or Word object when the document is rendered to those formats.\n",
    "supporting": [
      "qt_tables_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"t1_gt\",\"t1_gt\",\"t1_gt\",\"t1_gt\",\"t1_gt\",\"t1_gt\",\"t1_gt\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}